# Generated by Django 6.0.7 on 2026-07-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '😥 Awful'), (2, '☹️ Meh'), (3, '😑 okey'), (4, '😊 Good'), (5, '🤩 Amazing')])),
                ('note', models.TextField(blank=True, null=True)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
